### ISSUE TITLE
Game freezes on world creation

### ISSUE THREAD

**Issue by noamsm** [SilentChaos512/SilentLib#17]
# Versions
SilentLib: 4.4.0+44
SilentGems: 3.4.6+79
SilentGear: 1.4.3+68
SilentMechanisms: 0.6.4+35
Forge: 28.1.44

# Description
When trying to create a new world (buffet generator), the game freezes and then crashes with this exception:
`java.lang.ClassCastException: com.alcatrazescapee.lastsupper.capability.PlayerData$Provider cannot be cast to net.silentchaos512.gems.api.chaos.IChaosSource`

This is the crash log:
```---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 10/12/19 6:05 PM
Description: Ticking player

java.lang.ClassCastException: com.alcatrazescapee.lastsupper.capability.PlayerData$Provider cannot be cast to net.silentchaos512.gems.api.chaos.IChaosSource
	at net.silentchaos512.gems.network.GeneralSyncPacket$$Lambda$7397/742729140.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at net.silentchaos512.gems.network.GeneralSyncPacket.<init>(GeneralSyncPacket.java:27) ~[?:3.4.5+78] {re:classloading}
	at net.silentchaos512.gems.network.NetworkEvents.onPlayerTick(NetworkEvents.java:19) ~[?:3.4.5+78] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_400_NetworkEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:205) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.silentchaos512.gems.network.GeneralSyncPacket$$Lambda$7397/742729140.accept(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
	at net.silentchaos512.gems.network.GeneralSyncPacket.<init>(GeneralSyncPacket.java:27)
	at net.silentchaos512.gems.network.NetworkEvents.onPlayerTick(NetworkEvents.java:19)
	at net.minecraftforge.eventbus.ASMEventHandler_400_NetworkEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:205)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 361
	Entity Name: Blue_future
	Entity's Exact location: -6.50, 84.00, -2.50
	Entity's Block location: World: (-7,84,-3), Chunk: (at 9,5,13 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@3f974ff4
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1370146456 bytes (1306 MB) / 4951900160 bytes (4722 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.44.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.44.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.44.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.44.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.44.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.44
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotori_scala@2.13.1
	Mod List: 
		acceleratorcraft-1.1.2.jar AcceleratorCraft {acceleratorcraft@1.1.2 DONE}
		AdditionalEnchantedMiner-1.14.4-14.0.9.jar QuarryPlus {quarryplus@14.0.9 DONE}
		AdvancedSkinCustomization-2.0.2.jar Advanced Skin Customization {advskinmod@2.0.2 DONE}
		alib-1.14.4-7.jar A Lib {alib@1.14.4-7 DONE}
		angelring-1.14.4-1.0.1.jar Angel Ring {angelring@1.0.1 DONE}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		Arcana BETA-0.0.1.jar Arcana {arcana@BETA-0.0.1 DONE}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 DONE}
		BadMobs-1.14.4-3.0.1.jar BadMobs {badmobs@3.0.1 DONE}
		BetterAnimationsCollection2-v1.1b4-1.14.4.jar Better Animations Collection 2 {betteranimationscollection2@1.1b4 DONE}
		BetterSigns-1.0_v1.14.4.jar Better Signs {bettersigns@1.0 DONE}
		BiomesOPlenty-1.14.4-9.0.0.254-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.254 DONE}
		blockdrops-1.14.4-1.0.2.jar Block Drops {blockdrops@1.0.2 DONE}
		ChanceCubes-1.14.4-4.0.0.298.jar Chance Cubes {chancecubes@1.14.4-4.0.0.298 DONE}
		chunkloader-1.14.4-1.0.0.jar Chunk Loader {chunkloader@1.14.4-1.0.0 DONE}
		ChunkNoGoByeBye-1.14.4-1.0.3.jar ChunkNoGoByeBye {chunknogobyebye@1.14.4-1.0.3 DONE}
		clayconversion-1.14-1.0.jar Clay Conversion {clayconversion@1.0 DONE}
		ClickMachine-1.14.4-2.1.2.jar Click Machine {clickmachine@2.1.2 DONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 DONE}
		ComPatchedStorage-1.14.4-2.1.4.jar ComPatchedStorage {compatchedstorage@2.1.4 DONE}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 DONE}
		CraftingTweaks_1.14.4-10.1.3.jar Crafting Tweaks {craftingtweaks@10.1.3 DONE}
		CraftTweaker-1.14.4-5.0.0.jar CraftTweaker {crafttweaker@1.14.4-5.0.0 DONE}
		create-mc1.14.4_v0.1.1.jar Create {create@0.1.1 DONE}
		Cyclic-1.14.4-0.0.12.jar Cyclic {cyclic@1.14.4-0.0.12 DONE}
		dankstorage-1.5a.jar Dank Storage {dankstorage@1.5a DONE}
		deathquotes-1.2-1.14.4.jar DeathQuotes {deathquotes@1.0 DONE}
		DecorationControl-1.14.4-1.1.0.jar DecorationControl {decoctrl@1.1.0 DONE}
		DefaultOptions_1.14.4-10.2.6.jar Default Options {defaultoptions@10.2.6 DONE}
		Dirt2Path-1.0.0.jar Dirt2Path {d2p@1.0.0 DONE}
		DoggyTalents-1.14.4-1.15.2.0.jar Doggy Talents {doggytalents@1.15.2.0 DONE}
		EnchantmentDescriptions-1.14.4-1.3.6.jar EnchantmentDescriptions {enchdesc@1.3.6 DONE}
		endteleporters-1.1.1-1.14.4.jar End Teleporters {endteleporters@1.1.1 DONE}
		essentials-1.14.4-2.6.0.jar Essentials {essentials@1.14.4-2.6.0 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		Fence Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version DONE}
		fishtraps-0.0.4.jar Fish Traps {fishtraps@1.14.4-0.0.4 DONE}
		flying_things-1.8.5-1.14.4.jar The Flying Things {flying_things@1.8.5 DONE}
		FpsReducer-mc1.14.4-1.13.jar FPS Reducer {fpsreducer@mc1.14.4-1.13 DONE}
		FriendlyFire-1.14.4-3.0.1.jar FriendlyFire {friendlyfire@3.0.1 DONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 DONE}
		globaldatapack-1.14.4-1.2.1.jar Dark Roleplay - Global Datapacks {globaldatapack@1.14.4-1.2 DONE}
		gravestone-1.15.2.jar Gravestone Mod {gravestone@1.15.2 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		Heaven Paradise Plant ver1.2.jar Heaven Paradise Plant {heavenparadiseplantmod@1.0.0 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		inventorysorter-1.14.4-16.1.0.jar Simple Inventory Sorter {inventorysorter@16.1.0 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		jei-1.14.4-6.0.0.18.jar Just Enough Items {jei@6.0.0.18 DONE}
		KleeSlabs_1.14.4-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 DONE}
		lastsupper-forge-1.14.4-1.0.0.jar Last Supper {lastsupper@1.0.0 DONE}
		Mantle-1.14.4-1.4.32.jar Mantle {mantle@1.4.32 DONE}
		MCFurnace-1.14.4-DEV-1.3.2.jar MCFurnace {mcfurnace@1.3.0 DONE}
		mcjtylib-1.14-3.5.7-alpha.jar McJtyLib {mcjtylib@NONE DONE}
		Morpheus-1.14.4-4.2.43.jar Morpheus {morpheus@version DONE}
		MouseTweaks-2.12-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.12 DONE}
		OreExcavation-1.6.141.jar Ore Excavation {oreexcavation@1.6.141 DONE}
		overloadedarmorbar-3.0.0.jar Example Mod {overloadedarmorbar@3.0.0 DONE}
		ParticleFixes-v1.1-1.14.4.jar Particle Fixes {particlefixes@1.1 DONE}
		petbat-1.14.4.2.jar Pet Bat {petbat@1.14.3.1 DONE}
		Placebo-1.14.4-2.3.1.jar Placebo {placebo@2.3.1 DONE}
		portality-1.14.4-2.0.0-5f9c6a1.jar Portality {portality@NONE DONE}
		quirkygenerators-1.4.jar Quirky Generators {quirkygenerators@1.4 DONE}
		randompatches-1.14.4-1.19.1.1.jar RandomPatches {randompatches@1.14.4-1.19.1.1 DONE}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 DONE}
		restrictions-1.14-1.3.4-alpha.jar Restrictions {restrictions@NONE DONE}
		rftoolsbase-1.14-0.0.4-alpha.jar RFToolsBase {rftoolsbase@NONE DONE}
		rftoolspower-1.14-1.2.4-alpha.jar RFToolsPower {rftoolspower@NONE DONE}
		rftoolsutility-1.14-1.2.4-alpha.jar RFToolsUtility {rftoolsutility@NONE DONE}
		RingOfAttraction-1.14.4-1.0.16.jar Ring of Attraction {ring_of_attraction@1.0.16 DONE}
		RingOfBlink-1.14.4-1.0.19.jar Ring of Blink {ring_of_blink@1.0.19 DONE}
		RingOfGrowth-1.14.4-1.0.17.jar Ring of Growth {ring_of_growth@1.0.17 DONE}
		RingOfMiner-1.14.4-1.0.14.jar Ring of Miner {ring_of_miner@1.0.14 DONE}
		RingOfRepair-1.14.4-1.0.17.jar Ring of Repair {ring_of_repair@1.0.17 DONE}
		RingOfTeleport-1.14.4-1.0.15.jar Ring of Teleport {ring_of_teleport@1.0.15 DONE}
		rsgauges-1.14.4-1.1.8-b4.jar Redstone Gauges and Switches {rsgauges@1.1.8-b4 DONE}
		SilentGear-1.14.4-1.4.3+68.jar Silent Gear {silentgear@1.4.3+68 DONE}
		SilentGems-1.14.4-3.4.5+78.jar Silent's Gems 3 {silentgems@3.4.5+78 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		SilentMechanisms-1.14.4-0.6.4+35.jar Silent's Mechanisms {silents_mechanisms@0.6.4+35 DONE}
		SimpleStorageNetwork-1.14.4-0.0.13.jar Simple Storage Network {storagenetwork@1.14.4-0.0.13 DONE}
		smooth-scrolling-everywhere-1.1.jar Smooth Scrolling Everywhere {smooth-scrolling-everywhere@1.1 DONE}
		speedyhoppers-1.14.4-6.jar Speedy Hoppers {speedyhoppers@1.14.4-6 DONE}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
		titanium-1.14.4-2.2.0-d9775a7.jar Titanium {titanium@1.14.4-2.2.0-d9775a7 DONE}
		TMechworks-1.14.4-2.0-beta2.jar Tinkers' Mechworks {tmechworks@2.0-beta2 DONE}
		TrashSlot_1.14.4-10.4.7.jar TrashSlot {trashslot@10.4.7 DONE}
		tubesreloaded-1.14.4-1.1.0b.jar Tubes Reloaded {tubesreloaded@1.14.4-1.1.0b DONE}
		twitchspawn1.14.4-1.4.4.jar TwitchSpawn {twitchspawn@1.4.4 DONE}
		Uppers-0.1.10.jar Uppers {uppers@0.1.10 DONE}
		villagerhats-1.14.4-1.1.1.jar Villager Hats {villagerhats@1.14.4-1.1.1 DONE}
		Xaeros_Minimap_1.18.4_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.18.4 DONE}
		xercamusic-1.14.4-1.2.jar Xerca's Music Mod {xercamusic@1.14.4-1.2 DONE}
		XL-Food-Mod-1.14.4-2.1.0.jar XL Food Mod {xlfoodmod@2.1.0 DONE}
		forge-1.14.4-28.1.44-universal.jar Forge {forge@28.1.44 DONE}
		forge-1.14.4-28.1.44-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Blue_future'/361, l='Newest Test', x=-6.50, y=84.00, z=-2.50]]
	Data Packs: vanilla, mod:acceleratorcraft, mod:advskinmod, mod:alib, mod:angelring, mod:appleskin, mod:arcana, mod:attributefix, mod:badmobs, mod:betteranimationscollection2, mod:bettersigns, mod:biomesoplenty, mod:blockdrops, mod:chancecubes (incompatible), mod:chunkloader, mod:chunknogobyebye, mod:clayconversion, mod:clickmachine, mod:clumps, mod:compatchedstorage, mod:controlling, mod:craftingtweaks, mod:crafttweaker, mod:create, mod:cyclic, mod:d2p, mod:dankstorage, mod:deathquotes, mod:decoctrl, mod:defaultoptions, mod:doggytalents, mod:enchdesc, mod:endteleporters, mod:essentials, mod:fastleafdecay, mod:fencejumper, mod:fishtraps, mod:flying_things, mod:forge, mod:fpsreducer, mod:friendlyfire, mod:ftbbackups, mod:globaldatapack, mod:gravestone, mod:harvest, mod:heavenparadiseplantmod, mod:inventorysorter, mod:ironchest, mod:jei, mod:kleeslabs, mod:lastsupper, mod:mantle, mod:mcfurnace, mod:mcjtylib, mod:morpheus, mod:mousetweaks, mod:oreexcavation, mod:overloadedarmorbar, mod:particlefixes, mod:petbat, mod:placebo, mod:portality (incompatible), mod:quarryplus, mod:quirkygenerators, mod:randompatches, mod:randomthings, mod:restrictions, mod:rftoolsbase, mod:rftoolspower, mod:rftoolsutility, mod:ring_of_attraction, mod:ring_of_blink, mod:ring_of_growth, mod:ring_of_miner, mod:ring_of_repair, mod:ring_of_teleport, mod:rsgauges, mod:silentgear, mod:silentgems, mod:silentlib, mod:silents_mechanisms, mod:smooth-scrolling-everywhere, mod:speedyhoppers, mod:storagedrawers, mod:storagenetwork, mod:titanium (incompatible), mod:tmechworks, mod:trashslot, mod:tubesreloaded, mod:twitchspawn, mod:uppers, mod:villagerhats, mod:waila, mod:xaerominimap, mod:xercamusic, mod:xlfoodmod, modpack:Wizardry-1.2.zip
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge' ```

**Comment by SilentChaos512** [comment]
Looks like an issue with The Last Supper's capabilities. Not sure what exactly is happening here. It's probably the same issue as https://github.com/alcatrazEscapee/last-supper/issues/1.
