### ISSUE TITLE
Crash Report for the new BETA.

### ISSUE THREAD

**Issue by WilliamBlaze** [SilentChaos512/SilentLib#9]
I figured since its out i'd test it and report back any errors/bugs. And this crash occurred during the mod loader start up. Just doing my part to help; even if its not much help.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  PistonExpansionLoadingPlugin (pistonexpansion-1.12.2-1.0.1-core.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
  Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.8.jar)
  AstralCore (astralsorcery-1.12.2-1.8.9.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.12-93.jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.1.5-universal.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.5.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 5/1/18 10:24 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.silentchaos512.lib.registry.SRegistry.registerSoundEvent(Lnet/minecraft/util/SoundEvent;)V
	at net.silentchaos512.scalinghealth.init.ModSounds.registerAll(ModSounds.java:16)
	at net.silentchaos512.lib.registry.SRegistry$EventHandler.registerSoundEvents(SRegistry.java:463)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_380_EventHandler_registerSoundEvents_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

All of your mods are great btw; its why i felt like doing a part to help in what way i can.

**Comment by SilentChaos512** [comment]
Looks like you may be using an outdated version of Scaling Heatlh. Try updating to 1.3.14.

**Comment by WilliamBlaze** [comment]
that's the thing though; i was using ScalingHealth-1.12-1.3.14-96.jar when this occurred.

**Comment by WilliamBlaze** [comment]
ah; scaling health in my mods folder wasn't switched out from 13.12.94 to 13.14.96 - user error on my part'
It seems to be functioning as intended now after correcting that mistake. At the very least Minecraft hasn't crashed out yet on the load up screen like last time; so all signs point to it functioning successfully so far.
